const $=s=>document.querySelector(s),sleep=ms=>new Promise(r=>setTimeout(r,ms));
const T={
en:{greet:"Namaste! I'm your Citizen-Service Agent. I'll handle the whole application, but I'll ask your permission before every sensitive step. Which service do you need?",docs:"I need 3 documents. Upload each one (or use a sample). I check every file before moving on.",dA:"Aadhaar card",dB:"Address proof",dC:"Income declaration",ok:"✓ {0} looks good.",bad:"✗ {0}: {1} Please upload again.",rT:"Only PDF, JPG or PNG allowed.",rS:"File is over 2 MB.",r1:"Image is blurry; number unreadable.",r2:"Document is older than 3 months.",r3:"Signature is missing.",c1:"Permission 1 of 2 — May I read your 3 documents and extract name, address and income to fill the form? Nothing goes to the portal yet.",c2:"Permission 2 of 2 — May I submit this application to the e-District portal and e-sign it for you? Shared: name, address, income, masked Aadhaar.",allow:"Allow",deny:"Deny",gA:"Consent {0} granted: {1}.",gD:"Consent {0} denied: {1}. I did not take that step.",filled:"I filled the form on the portal. Please check it.",stop1:"Understood — I won't read your documents. You can restart or ask for a human helper.",stop2:"Draft saved, not submitted. Type 'submit' when you're ready.",sub:"Submitting… attempt {0}/3",fail:"Portal not responding (attempt {0}). Retrying with backoff.",esc:"Still failing after 3 tries, so I'm handing over to a human helper. Ticket {0}. I passed them a summary; you won't repeat anything.",res:"Helper fixed the issue (simulated). Retrying…",done:"Submitted! Reference {0}. I'll track it for you.",st:["Received","Documents verified","Officer review","Certificate issued"],issued:"🎉 Certificate issued. Task complete.",fb:"I understand: yes / no, status, retry, human.",stat:"Current status: {0}.",ph:"Type or speak…",svc:["Income Certificate","Caste Certificate","Ration Card"],up:"Upload",sy:"Sample ✓",sn:"Sample ✗",hv:"Helper fixed it (simulate)",wait:"waiting",human:"Connecting you to a human helper…",pick:"Service selected: {0}"},
hi:{greet:"नमस्ते! मैं आपका नागरिक-सेवा एजेंट हूँ। पूरा आवेदन मैं संभालूँगा, लेकिन हर संवेदनशील कदम से पहले आपकी अनुमति लूँगा। आपको कौन-सी सेवा चाहिए?",docs:"मुझे 3 दस्तावेज़ चाहिए। हर एक अपलोड करें (या सैंपल चुनें)। आगे बढ़ने से पहले मैं हर फ़ाइल जाँचूँगा।",dA:"आधार कार्ड",dB:"पते का प्रमाण",dC:"आय घोषणा",ok:"✓ {0} सही है।",bad:"✗ {0}: {1} कृपया दोबारा अपलोड करें।",c1:"अनुमति 1/2 — क्या मैं आपके 3 दस्तावेज़ पढ़कर नाम, पता और आय निकाल सकता हूँ? अभी पोर्टल पर कुछ नहीं भेजा जाएगा।",c2:"अनुमति 2/2 — क्या मैं यह आवेदन ई-डिस्ट्रिक्ट पोर्टल पर जमा करके आपकी ओर से ई-साइन कर सकता हूँ?",allow:"अनुमति दें",deny:"मना करें",filled:"मैंने पोर्टल पर फ़ॉर्म भर दिया है। कृपया जाँच लें।",esc:"3 कोशिशों के बाद भी समस्या है, इसलिए मैं मानव सहायक को सौंप रहा हूँ। टिकट {0}। सारांश उन्हें दे दिया है।",done:"जमा हो गया! संदर्भ संख्या {0}। मैं स्थिति ट्रैक करूँगा।",st:["प्राप्त","दस्तावेज़ सत्यापित","अधिकारी समीक्षा","प्रमाणपत्र जारी"],issued:"🎉 प्रमाणपत्र जारी हो गया। काम पूरा।",fb:"मैं समझता हूँ: हाँ / नहीं, स्थिति, दोबारा, मदद।",ph:"लिखें या बोलें…",svc:["आय प्रमाणपत्र","जाति प्रमाणपत्र","राशन कार्ड"],up:"अपलोड",sy:"सैंपल ✓",sn:"सैंपल ✗",r1:"तस्वीर धुँधली है।",r2:"दस्तावेज़ 3 महीने से पुराना है।",r3:"हस्ताक्षर नहीं है।"},
hn:{greet:"Namaste! Main aapka Citizen-Service Agent hoon. Poora application main handle karunga, par har sensitive step se pehle aapki permission loonga. Kaunsi service chahiye?",docs:"Mujhe 3 documents chahiye. Har ek upload karein (ya sample use karein). Aage badhne se pehle main check karunga.",dA:"Aadhaar card",dB:"Address proof",dC:"Income declaration",ok:"✓ {0} sahi hai.",bad:"✗ {0}: {1} Please dobara upload karein.",c1:"Permission 1/2 — Kya main aapke 3 documents padh kar naam, address aur income nikaal sakta hoon? Abhi portal par kuch nahi jaayega.",c2:"Permission 2/2 — Kya main application portal par submit karke aapki taraf se e-sign kar doon?",allow:"Allow karein",deny:"Mana karein",filled:"Maine portal par form bhar diya. Please check kar lein.",esc:"3 try ke baad bhi problem hai, isliye human helper ko de raha hoon. Ticket {0}. Summary unhe de di hai.",done:"Submit ho gaya! Reference {0}. Main status track karunga.",st:["Received","Documents verified","Officer review","Certificate issued"],issued:"🎉 Certificate issue ho gaya. Kaam complete.",fb:"Main samajhta hoon: haan / nahi, status, retry, madad.",ph:"Likhein ya bolein…",svc:["Income Certificate","Caste Certificate","Ration Card"],up:"Upload",sy:"Sample ✓",sn:"Sample ✗",r1:"Image blurry hai.",r2:"Document 3 mahine se purana hai.",r3:"Signature missing hai."}};
const VL={en:"en-IN",hi:"hi-IN",hn:"en-IN"};
let L="en",speak=false,S,chain=[],M;
const t=(k,...a)=>{let s=(T[L][k]??T.en[k]);if(Array.isArray(s))return s;return s.replace(/\{(\d)\}/g,(_,i)=>a[i])};
function init(){S={svc:null,docs:{A:0,B:0,C:0},pending:null,ref:null,stage:-1,busy:false,sent:false,draft:false,filled:false};M={steps:0,cons:0,ret:0,esc:0,den:0,res:"—"};chain=[];$("#chat").innerHTML="";$("#log").innerHTML="";$("#dl").disabled=true;$("#ref").textContent="";$("#pst").textContent="● idle";["name","fn","addr","inc","aad"].forEach(x=>$("#f_"+x).value="");renderTL();kpi();log("system","session_start","Agent session started");say(t("greet"));svcBtns()}
function kpi(){$("#k1").textContent=M.steps;$("#k2").textContent=M.cons;$("#k3").textContent=M.ret;$("#k4").textContent=M.esc;$("#k5").textContent=M.den;$("#k6").textContent=M.res}
async function sha(s){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function log(actor,action,detail,cls=""){const e={n:chain.length+1,ts:new Date().toISOString(),actor,action,detail,prev:chain.length?chain[chain.length-1].hash:"0"};chain.push(e);e.hash=await sha(e.prev+e.n+e.ts+actor+action+detail);const d=document.createElement("div");d.className="lg "+cls;d.innerHTML=`<b>#${e.n} ${actor}</b> · ${action}<br><span></span><br><code>${e.ts.slice(11,19)} · ${e.hash.slice(0,12)}</code>`;d.querySelector("span").textContent=detail;$("#log").prepend(d)}
function msg(txt,cls){const d=document.createElement("div");d.className="m "+cls;d.textContent=txt;$("#chat").append(d);d.scrollIntoView({block:"end"});return d}
function say(txt){msg(txt,"a");if(speak&&"speechSynthesis"in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(txt);u.lang=VL[L];speechSynthesis.speak(u)}}
function card(html){const d=document.createElement("div");d.className="card";d.innerHTML=html;$("#chat").append(d);d.scrollIntoView({block:"end"});return d}
function btn(txt,fn,cls=""){const b=document.createElement("button");b.textContent=txt;b.className=cls;b.onclick=fn;return b}
function svcBtns(){const r=document.createElement("div");r.className="row";t("svc").forEach((n,i)=>r.append(btn(n,()=>pickSvc(n,r),"ghost")));$("#chat").append(r)}
function pickSvc(n,r){if(S.svc)return;S.svc=n;r.remove();msg(n,"u");log("user","select_service",n);M.steps++;kpi();say(t("docs"));docsCard()}
const DN={A:"dA",B:"dB",C:"dC"},BADR={A:"r1",B:"r2",C:"r3"};
function docsCard(){const c=card("");S.dc=c;drawDocs()}
function drawDocs(){const c=S.dc;c.innerHTML="";["A","B","C"].forEach(k=>{const r=document.createElement("div");r.className="doc";const st=S.docs[k]?`<span class="tag ok">✓</span>`:`<span class="tag wait">${t("wait")}</span>`;r.innerHTML=`<div><b>${t(DN[k])}</b> ${st}</div>`;const a=document.createElement("div");a.className="row";a.style.margin=0;if(!S.docs[k]){const f=document.createElement("input");f.type="file";f.accept=".pdf,.jpg,.jpeg,.png";f.setAttribute("aria-label",t("up")+" "+t(DN[k]));f.style.maxWidth="150px";f.onchange=()=>f.files[0]&&check(k,f.files[0]);a.append(f,btn(t("sy"),()=>check(k,{name:"sample.pdf",size:5e5,ok:1}),"ghost"),btn(t("sn"),()=>check(k,{name:"bad.jpg",size:5e5,ok:0}),"bad"))}r.append(a);c.append(r)})}
function check(k,f){let why=null;if(f.ok===undefined){if(!/\.(pdf|jpe?g|png)$/i.test(f.name))why=t("rT");else if(f.size>2e6)why=t("rS")}else if(!f.ok)why=t(BADR[k]);
if(why){log("agent","validate_doc_failed",t(DN[k])+": "+why,"fail");say(t("bad",t(DN[k]),why));return}
S.docs[k]=1;M.steps++;kpi();log("agent","validate_doc_ok",t(DN[k])+" ("+f.name+")","ok");say(t("ok",t(DN[k])));drawDocs();if(S.docs.A&&S.docs.B&&S.docs.C)consent(1)}
function consent(n){const id="C-00"+n,what=n==1?"read documents & extract data":"submit application & e-sign";S.pending={id,n,what};say(t("c"+n));const c=card(`<b>🔐 ${id}</b>`);const r=document.createElement("div");r.className="row";r.append(btn(t("allow"),()=>resolve(true,c)),btn(t("deny"),()=>resolve(false,c),"bad"));c.append(r);log("agent","consent_requested",id+": "+what,"consent")}
async function resolve(yes,c){if(!S.pending)return;const p=S.pending;S.pending=null;c&&c.remove();M.cons++;if(!yes)M.den++;kpi();log("user",yes?"consent_granted":"consent_denied",p.id+": "+p.what,"consent");say(t(yes?"gA":"gD",p.id,p.what));
if(p.n==1){if(!yes){say(t("stop1"));M.res="stopped";kpi();return}await sleep(500);fill();consent(2)}else{if(!yes){S.draft=true;say(t("stop2"));return}submit()}}
function fill(){const v={name:"Ayush Kumar",fn:"Rakesh Kumar",addr:"Sakchi, Jamshedpur, Jharkhand",inc:"96,000",aad:"XXXX XXXX 4821"};for(const k in v)$("#f_"+k).value=v[k];S.filled=1;M.steps++;kpi();log("agent","form_filled","5 fields filled from documents (Aadhaar masked)","ok");say(t("filled"))}
async function submit(){if(S.busy||S.sent)return;if(!S.filled){say(t("stop1"));return}S.busy=true;for(let a=1;a<=3;a++){$("#pst").textContent="● submitting";say(t("sub",a));await log("agent","portal_submit","attempt "+a);await sleep(700);if(!$("#out").checked){S.ref="JH-"+Math.floor(1e6+Math.random()*9e6);S.sent=true;S.busy=false;M.steps++;kpi();$("#ref").textContent="Ref: "+S.ref;log("portal","accepted","Reference "+S.ref,"ok");say(t("done",S.ref));track();return}
M.ret++;kpi();await log("portal","timeout","HTTP 503 on attempt "+a,"fail");if(a<3){say(t("fail",a));await sleep(600*a)}}
S.busy=false;M.esc++;kpi();$("#pst").textContent="● escalated";const id="H-"+Math.floor(1000+Math.random()*9000);log("agent","escalated_to_human",id+": 3 failed submits, docs validated, consent C-002 on file","fail");say(t("esc",id));const c=card(`<b>👤 ${id}</b><br>Handoff: ${S.svc}, 3 docs ✓, consents 2/2, portal 503 ×3`);c.append(btn(t("hv"),()=>{c.remove();$("#out").checked=false;log("human","resolved",id+" outage cleared","ok");say(t("res"));submit()},"ghost"))}
function renderTL(){const s=t("st");$("#tl").innerHTML=s.map((x,i)=>`<li class="${i<S.stage?"done":i==S.stage?"on":""}">${x}</li>`).join("")}
async function track(){const n=4;for(let i=0;i<n;i++){S.stage=i;renderTL();$("#pst").textContent="● "+t("st")[i];log("portal","status",t("st")[i],"ok");M.steps++;kpi();await sleep(2200)}S.stage=n;renderTL();$("#pst").textContent="● issued";$("#dl").disabled=false;M.res="✓ 100%";kpi();log("system","task_complete","End-to-end success","ok");say(t("issued"))}
function status(){say(t("stat",S.stage>=0?t("st")[Math.min(S.stage,3)]:"—"))}
function handle(x){x=x.trim();if(!x)return;msg(x,"u");const s=x.toLowerCase();log("user","message",x.slice(0,80));
const Y=/\b(yes|allow|ok|okay|sure|haan|han|theek|ji)\b|हाँ|हां|ठीक|अनुमति/,N=/\b(no|deny|nahi|nahin|mat|stop)\b|नहीं|मना/;
if(S.pending){if(Y.test(s))return resolve(true);if(N.test(s))return resolve(false)}
if(/human|help|madad|insaan|sahayak|मदद|सहायक/.test(s)){M.esc++;kpi();log("agent","escalated_to_human","User requested human helper","fail");return say(t("human"))}
if(/status|sthiti|स्थिति/.test(s))return status();
if(/submit|retry|dobara|jama|फिर|दोबारा|जमा/.test(s)){if(S.filled&&!S.sent)return submit()}
say(t("fb"))}
$("#snd").onclick=()=>{handle($("#txt").value);$("#txt").value=""};$("#txt").onkeydown=e=>{if(e.key==="Enter")$("#snd").click()};
$("#lang").onchange=e=>{L=e.target.value;document.documentElement.lang=L=="en"?"en":"hi";$("#txt").placeholder=t("ph");renderTL();log("user","language_changed",L)};
$("#spk").onclick=e=>{speak=!speak;e.target.setAttribute("aria-pressed",speak);e.target.textContent="🔈 Voice reply: "+(speak?"on":"off");if(!speak&&window.speechSynthesis)speechSynthesis.cancel()};
$("#rst").onclick=init;
$("#mic").onclick=()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return say("Voice input isn't supported in this browser. Please type instead.");const r=new R();r.lang=VL[L];r.onstart=()=>$("#mic").classList.add("rec");r.onend=()=>$("#mic").classList.remove("rec");r.onresult=e=>{const x=e.results[0][0].transcript;log("user","voice_input",x.slice(0,80));handle(x)};r.onerror=()=>$("#mic").classList.remove("rec");try{r.start()}catch(_){}};
$("#ver").onclick=async()=>{let ok=true,p="0";for(const e of chain){const h=await sha(p+e.n+e.ts+e.actor+e.action+e.detail);if(h!==e.hash||e.prev!==p){ok=false;break}p=e.hash}say(ok?`🔒 Audit chain verified: ${chain.length} entries intact.`:"⚠ Audit chain broken — tampering detected.")};
$("#exp").onclick=()=>{const a=document.createElement("a");a.href="data:application/json,"+encodeURIComponent(JSON.stringify(chain,null,2));a.download="audit-log.json";a.click()};
$("#dl").onclick=()=>{const a=document.createElement("a");a.href="data:text/plain,"+encodeURIComponent(`MOCK ${S.svc}\nRef: ${S.ref}\nIssued digitally (demo only)`);a.download=(S.ref||"certificate")+".txt";a.click();log("user","download_certificate",S.ref||"","ok")};
function applyTheme(m){document.documentElement.dataset.theme=m;try{localStorage.setItem("seva-theme",m)}catch(_){}$("#thm").textContent=m==="dark"?"☀️ Light":"🌙 Dark"}
let _m=null;try{_m=localStorage.getItem("seva-theme")}catch(_){}
applyTheme(_m||(matchMedia("(prefers-color-scheme:dark)").matches?"dark":"light"));
$("#thm").onclick=()=>applyTheme(document.documentElement.dataset.theme==="dark"?"light":"dark");
init();